# Generated by Django 2.0.6 on 2019-05-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tuser',
            options={},
        ),
    ]
