# Generated by Django 2.0.6 on 2019-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190525_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuser',
            name='status',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
