# Generated by Django 2.0.6 on 2019-05-26 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190525_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tconfirmstring',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.TUser'),
        ),
    ]
